# Generated by Django 2.1.4 on 2019-02-10 11:21

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_name', models.CharField(max_length=32)),
                ('goods_id', models.CharField(max_length=32)),
                ('goods_price', models.FloatField()),
                ('goods_now_price', models.FloatField()),
                ('goods_num', models.IntegerField()),
                ('goods_description', models.TextField()),
                ('goods_content', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_path', models.ImageField(upload_to='image')),
                ('img_label', models.CharField(max_length=32)),
                ('goods', models.ForeignKey(on_delete=True, to='Shops.Goods')),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('phone', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=32)),
                ('nickname', models.CharField(max_length=32)),
                ('photo', models.ImageField(upload_to='image')),
            ],
        ),
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=32)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='goods',
            name='seller',
            field=models.ForeignKey(on_delete=True, to='Shops.Seller'),
        ),
        migrations.AddField(
            model_name='goods',
            name='types',
            field=models.ForeignKey(on_delete=True, to='Shops.Types'),
        ),
    ]
