# Generated by Django 2.1.4 on 2019-02-15 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='taobao',
            field=models.CharField(default='', max_length=1024),
            preserve_default=False,
        ),
    ]
